# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import PrimaryPushButton
from PyQt5.QtGui import QPixmap, QImage,QIcon
import PIL
import numpy as np
from util import load_config
config = load_config()
class Main_Window(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(815, 460)
        self.Button3 = PrimaryPushButton(Form)
        self.Button3.setGeometry(QtCore.QRect(690, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button3.setFont(font)
        self.Button3.setObjectName("Button3")
        self.Image_label = QtWidgets.QLabel(Form)
        self.Image_label.setGeometry(QtCore.QRect(10, 40, 521, 391))
        self.Image_label.setText("")
        self.Image_label.setObjectName("Image_label")
        self.Button2 = PrimaryPushButton(Form)
        self.Button2.setGeometry(QtCore.QRect(550, 320, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button2.setFont(font)
        self.Button2.setObjectName("Button2")
        self.Button4 = PrimaryPushButton(Form)
        self.Button4.setGeometry(QtCore.QRect(550, 390, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button4.setFont(font)
        self.Button4.setObjectName("Button4")
        self.Button1 = PrimaryPushButton(Form)
        self.Button1.setGeometry(QtCore.QRect(550, 200, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button1.setFont(font)
        self.Button1.setObjectName("Button1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(550, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(640, 250, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.logo = QtWidgets.QLabel(Form)
        self.logo.setGeometry(QtCore.QRect(620, 64, 108, 108))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.Addbijin()
        self.AddLogo()
    # 加入背景图片
    def Addbijin(self):
        self.img = PIL.Image.open(config["bg1"])
        self.img = self.img.resize((521, 391))
        self.img = np.array(self.img)
        # rgb_image = cv2.cvtColor(self.img, cv2.COLOR_BGR2RGB)
        rgb_image = self.img
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        q_img = QImage(rgb_image.data, w, h, bytes_per_line, QImage.Format_RGB888)
        pixmap = QPixmap.fromImage(q_img)
        self.Image_label.setPixmap(pixmap)
    # 加入logo
    def AddLogo(self):
        self.img = PIL.Image.open(config["logo"])
        self.img = self.img.resize((108,108))
        self.img = np.array(self.img)
        # rgb_image = cv2.cvtColor(self.img, cv2.COLOR_BGR2RGB)
        rgb_image = self.img
        h, w, ch = rgb_image.shape
        bytes_per_line = ch * w
        q_img = QImage(rgb_image.data, w, h, bytes_per_line, QImage.Format_RGB888)
        pixmap = QPixmap.fromImage(q_img)
        self.logo.setPixmap(pixmap)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Button3.setText(_translate("Form", "删除"))
        self.Button2.setText(_translate("Form", "录入"))
        self.Button4.setText(_translate("Form", "更新模型"))
        self.Button1.setText(_translate("Form", "识别"))
        self.label_2.setText(_translate("Form", "显示结果："))
        self.label_3.setText(_translate("Form", "结果信息"))
